Task/sale 4
ianomokonov/sales-scripts pull request #2
Opened 2021-08-18 17:32 UTC by volik25

2021-08-18 19:26 UTC, ianomokonov requested changes

2021-08-18 19:26 UTC, ianomokonov commented on angular.json
> +    "analytics": "b9ce025f-b36b-4ffd-a6c3-0e79c1a30a7d",
Это зачем нужно?

2021-08-18 19:26 UTC, ianomokonov commented on src/app/app-routing.module.ts
> +    path: 'lk',
Мб лучше profile? Как-то несолидно lk

2021-08-18 19:26 UTC, ianomokonov commented on src/proxy.conf.json
> +    "secure": false
Надо ещё 

`"changeOrigin": true`

2021-08-19 17:37 UTC, volik25 commented on angular.json
> +    "analytics": "b9ce025f-b36b-4ffd-a6c3-0e79c1a30a7d",
Аналитика, удалю, наверное

2021-08-19 17:37 UTC, volik25 commented on src/app/app-routing.module.ts
> +    path: 'lk',
Принято

2021-08-20 08:16 UTC, ianomokonov approved these changes

2021-08-20 08:16 UTC, merged