Task/sale 8
ianomokonov/sales-scripts pull request #5
Opened 2021-08-26 20:34 UTC by volik25

Шаблоны форм реги и входа
Интерсептор, сервисы токена и пользователя

2021-08-27 10:29 UTC, ianomokonov requested changes

2021-08-27 10:29 UTC, ianomokonov commented on src/app/_services/front/auth.service.ts
> +  public refreshToken(token: string): Observable<string[]> {
Думаю этот метод лучше в users.service перенести и убрать отсюда импорт http
это все таки фронтовой сервис

2021-08-27 10:29 UTC, ianomokonov commented on src/app/components/sign-in/sign-in.component.ts
> +  private initForm() {
Зачем в метод, если один раз вызывается, думаю можно оставить в конструкторе

2021-08-27 10:29 UTC, ianomokonov commented on src/app/components/sign-up/sign-up.component.ts
> +  public passwordError = false;
Думаю это не очень правильно, ИМХО нужно написать валидатор на форму и на основе ошибки формы выводить сообщение об ошибке

2021-08-30 18:20 UTC, volik25 commented on src/app/components/sign-up/sign-up.component.ts
> +  public passwordError = false;
Я не помню, мы же решили не менять тут ничего?

2021-08-30 19:14 UTC, ianomokonov approved these changes

2021-08-30 19:18 UTC, merged