task: VolikIA/Sale-17
ianomokonov/sales-scripts pull request #8
Opened 2021-09-02 14:09 UTC by volik25

Дерево директорий + добавление новой директории

2021-09-02 17:41 UTC, ianomokonov requested changes

2021-09-02 17:41 UTC, ianomokonov commented on src/app/_services/back/script.service.ts
> +  public getScripts(filters?: any): Observable<Script[]> {
Договорились вынести получение папок в отдельный метод getFolders
Параметр filters можно оставить для дальнейшей реализации фильтров

2021-09-02 17:41 UTC, ianomokonov commented on src/app/_services/back/script.service.ts
> +    return this.http.get<Script[]>(`${this.baseUrl}/script`, { params: filters });
строка должна быть ${this.baseUrl}/scripts
потому что получаешь список

2021-09-03 22:36 UTC, ianomokonov requested changes

2021-09-03 22:36 UTC, ianomokonov commented on src/app/modules/personal-cabinet/_modals/add-script/add-script.component.ts
> +    this.scriptService.getFolders().subscribe((folders) => {
Нужно перенести загрузку в родительский компонент и передавать сюда в конфиге, чтоб не грузить при каждом открытии модалки

В создании папки также

2021-09-03 22:36 UTC, ianomokonov commented on src/app/modules/personal-cabinet/_modals/add-script/add-script.component.ts
> +    this.scriptForm = fb.group({
у нас получается два одинаковых компонента? думаю нужно объединить в один
Два пути вижу, либо в конфиг передавать флаг isFolder и на основе него выбиарть какой запрос отправлять, либо добавить на форму switch (писал в задаче https://trello.com/c/5Bggn19p/16-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F-%D1%81%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%B0) типо что создаем, папку или скрипт

Думаю первый вариант лучше

2021-09-03 22:36 UTC, ianomokonov commented on src/app/components/sign-in/sign-in.component.html
> +                 [class.p-filled]='logInForm.controls.login.value'
такое на работает, думаю нужно через ngClass написать, потому что в таком синтаксисе дефисы не читаются

![image](https://user-images.githubusercontent.com/25670622/132071398-e6cb473e-2a75-41d3-80c4-57dea6d37f42.png)

2021-09-03 22:36 UTC, ianomokonov commented on src/app/components/sign-in/sign-in.component.html
> +                 [class.p-filled]='logInForm.controls.login.value'
Это касается всех полей

2021-09-04 13:20 UTC, volik25 commented on src/app/components/sign-in/sign-in.component.html
> +                 [class.p-filled]='logInForm.controls.login.value'
Наоборот через ngClass не работает, а в таком формате всё по кайфу

2021-09-04 13:20 UTC, volik25 commented on src/app/components/sign-in/sign-in.component.html
> +                 [class.p-filled]='logInForm.controls.login.value'
У тебя что-то не то

2021-09-04 13:22 UTC, volik25 commented on src/app/components/sign-in/sign-in.component.html
> +                 [class.p-filled]='logInForm.controls.login.value'
![image](https://user-images.githubusercontent.com/45817026/132095890-673500d4-b47d-4549-aadb-377579b095fa.png)

2021-09-04 13:23 UTC, volik25 commented on src/app/components/sign-in/sign-in.component.html
> +                 [class.p-filled]='logInForm.controls.login.value'
Либо же автокомплит - это не запись в value контрола и его надо нахуй запретить

2021-09-04 13:29 UTC, ianomokonov commented on src/app/components/sign-in/sign-in.component.html
> +                 [class.p-filled]='logInForm.controls.login.value'
Поменяй лейблы тогда, баг не исправлен

2021-09-05 09:27 UTC, closed without merging